'\" t
.\"     Title: cjdrouted
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 04/01/2012
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "CJDROUTED" "1" "04/01/2012" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cjdrouted \- Daemon control over cjdroute\&.
.SH "SYNOPSIS"
.sp
\fBcjdrouted\fR [start|stop|reconfigure|start\-default|killtunnel]
.SH "DESCRIPTION"
.sp
The cjdrouted(1) command provides shortcuts for manipulating the cjdroute process, as well as creating and destroying tunnel devices\&.
.SH "SUBCOMMANDS"
.PP
\fBstart\fR
.RS 4
Make sure /etc/cjdroute\&.conf exists, use it to run cjdroute, and log it all to both log locations using cjdlog\&.
.RE
.PP
\fBstop\fR
.RS 4
Kill the daemon process\&. Simply a call to
killall cjdroute, so if you\(cqre one of those brave/strange people who want to run multiple instances on the same OS\&... yet another reason cjdrouted will not get along with your multi\-noding fringe behavior\&. Don\(cqt get me wrong, though, you can do this in VMs just fine, but on the same OS, you\(cqre gonna have to get manual\&.
.RE
.PP
\fBreconfigure\fR
.RS 4
Shortcut alias for
\fIcjdrouted stop && cjdrouted start\fR\&.
.RE
.PP
\fBstart\-default\fR
.RS 4
Merges default peers into config before calling
\fIcjdrouted start\fR\&.
.RE
.PP
\fBkilltunnel\fR
.RS 4
Remove the tunnel named by
cjdinfo tunnel
.RE
.SH "BUGS"
.sp
See https://github\&.com/campadrenalin/cjdns\-deb/issues
.SH "AUTHOR"
.sp
cjdrouted was written by Philip Horger in 2012\&. cjdroute was written by Caleb Delisle\&.
.SH "RESOURCES"
.sp
Github: https://github\&.com/campadrenalin/cjdns\-deb/
.SH "COPYING"
.sp
Copyright (C) 2012 Philip Horger\&. Free use of this software is granted under the terms of the GNU General Public License (GPL)\&.
